name: quantum-drl-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - notebook
  - pennylane            # PennyLane for quantum machine learning
  - pennylane-qiskit     # PennyLane plugin for Qiskit
  - pennylane-lightning  # PennyLane plugin for optimized simulation
  - tensorflow           # TensorFlow for deep learning
  - pytorch              # PyTorch for reinforcement learning (DRL)
  - matplotlib           # For plotting results
  - numpy                # NumPy for numerical computations
  - scipy                # SciPy for scientific computations
  - pip                  # Include pip to install additional packages
  - nbgitpuller

  - pip:
    - stable-baselines3  # DRL library for TensorFlow/PyTorch
    - gym                # OpenAI Gym for reinforcement learning environments
    - pennylane            # PennyLane for quantum machine learning
    - pennylane-qiskit     # PennyLane plugin for Qiskit
    - pennylane-lightning  # PennyLane plugin for optimized simulation
